keys:
  - &user0 age1l4wz6djjwrev5y4pkrfu9lz7qukuwcsl4cghujg4m7wm3l37yp4saeajj8
  - &user1 age13rzm8legd2efdc202vrp06jgunf0qn2ecx5and20ff5pwg8t8gnq2m7jzd
  - &deck 62F580BEC408A2DAC14D4C0C1311C65498CF3427
  - &desktop 1D3443103716D82E840382FCCC5E009CE6212C60
  - &work 860FDFF5DCC9CF2315EE42DA2E376FD0794F56D3
  - &thinkpad CBF6FE1AEF7B62E89D5DB72FAED2B42C5260193A
creation_rules:
  - key_groups:
      - age:
          - *user0
          - *user1
        pgp:
          - *desktop
          - *deck
          - *work
          - *thinkpad
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *user0
          - *user1
        pgp:
          - *desktop
          - *deck
          - *work
          - *thinkpad