# https://taskfile.dev

version: '3'

silent: false

tasks:
  default:
    deps:
      - help

  nixos:
    desc: Enable NixOS config for current device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'apps/**/*'
      - 'flake/*'
      - 'hosts/**/*'
      - 'lib/*'
      - 'modules/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      - if [ -f '/etc/NIXOS' ]; then nixos-rebuild switch --use-remote-sudo --flake ".#$(hostname)" --show-trace; fi

  home-manager:
    aliases: [hm apply]
    desc: Enable home-manager config for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'flake/*'
      - 'hosts/home/**/*'
      - 'modules/home/**/*'
      - 'modules/nixos/home/default.nix'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    deps:
      - 'nixos'
    cmds:
      # Using hostname simplify flake option, see https://discourse.nixos.org/t/get-hostname-in-home-manager-flake-for-host-dependent-user-configs/18859/2
      # Using 'HM_HOST_SLUG=' in '.env' allows for building for specific host on any machine
      - nix run '.#home-manager' -- switch -b backup --show-trace --flake ".#${USER}@${HM_HOST_SLUG}"

  home-manager-news:
    aliases: [news]
    desc: Show home manager news
    cmds:
      - nix run '.#home-manager' -- news --flake ".#${USER}@${HM_HOST_SLUG}"

  test:
    aliases: [dry-activate]
    desc: Make sure NixOS and/or home-manager will work for current user and device
    cmds:
      - nix run '.#dry-activate'

  check:
    desc: Check flake for errors
    cmds:
      - nix flake check -L

  update:
    desc: Bump dependencies
    cmds:
      - nix run .#update-flake-inputs   
      - nix run .#commit-nvfetcher -L

  help:
    desc: List available tasks
    cmds:
      - task --list-all