# https://taskfile.dev

version: '3'

silent: false

tasks:
  default:
    deps:
      - help

  nixos:
    aliases:
      - switch
    desc: Enable NixOS config for current device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'apps/**/*'
      - 'flake/*'
      - 'hosts/**/*'
      - 'lib/*'
      - 'modules/nixos/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      - |-
        [ -f "/etc/NIXOS" ] && nixos-rebuild switch --use-remote-sudo --flake ".#$(hostname)" --show-trace

  home-manager:
    aliases: 
      - apply
      - hm
    desc: Enable home-manager config for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'flake/*'
      - 'hosts/home/**/*'
      - 'modules/home/**/*'
      - 'modules/nixos/home/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    deps:
      - nixos
    cmds:
      # Using 'HM_HOST_SLUG=' in '.env' allows for building for specific host on any machine
      - nix run .#home-manager -- switch -b backup --show-trace --flake ".#${USER}@${HM_HOST_SLUG}"

  home-manager-only:
    aliases: 
      - hm-only
    desc: Enable home-manager config for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'flake/*'
      - 'hosts/home/**/*'
      - 'modules/home/**/*'
      - 'modules/nixos/home/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      # Using 'HM_HOST_SLUG=' in '.env' allows for building for specific host on any machine
      - nix run .#home-manager -- switch -b backup --show-trace --flake ".#${USER}@${HM_HOST_SLUG}"

  test:
    aliases: 
      - dry-activate
    desc: Make sure NixOS and/or home-manager will work for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'apps/**/*'
      - 'flake/*'
      - 'hosts/**/*'
      - 'lib/*'
      - 'modules/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      - nix run .#dry-activate

  home-manager-news:
    aliases: 
      - news
    desc: Show home-manager news
    cmds:
      - nix run .#home-manager -- news --flake ".#${USER}@${HM_HOST_SLUG}"

  check:
    desc: Check flake for errors
    cmds:
      - nix flake check -L

  update:
    desc: Bump dependencies
    cmds:
      - nix run .#update-flake-inputs   
      - nix run .#commit-nvfetcher -L

  help:
    desc: List available tasks
    cmds:
      - task --list-all