# https://taskfile.dev

version: '3'

silent: false

tasks:
  default:
    deps:
      - help

  nixos:
    aliases:
      - switch
      - apply-nixos
    desc: Enable NixOS config for current device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'apps/**/*'
      - 'flake/*'
      - 'hosts/**/*'
      - 'lib/*'
      - 'modules/nixos/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds: 
      - |-
        [ -f "/etc/NIXOS" ] && nixos-rebuild switch --use-remote-sudo --flake . --show-trace

  home-manager:
    aliases: 
      - hm
    desc: Enable home-manager config for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'flake/*'
      - 'hosts/homes/**/*'
      - 'modules/home/**/*'
      - 'modules/nixos/home/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      # Using 'HM_HOST_SLUG=' in '.env' allows for building for specific host on any machine
      - nix run .#home-manager -- switch -b backup --show-trace --flake ".#${USER}@${HM_HOST_SLUG:-$(hostname)}"

  apply:
    desc: Enable NixOS and home-manager configuration for current user and device
    cmds: 
      - task: nixos
      # Force home-manager switch, since previous task might remove current home-manager configuration
      - task -f home-manager

  test-nixos:
    desc: Try to build NixOS config for current user and device
    aliases:
      - nixos-dry-run
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'apps/**/*'
      - 'flake/*'
      - 'hosts/**/*'
      - 'lib/*'
      - 'modules/nixos/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      # Prefer `build` rather than `test` and `dry-reactivate` for the speed and not requiring root permissions
      - nixos-rebuild build --flake . --show-trace

  test-home-manager:
    aliases:
      - home-manager-dry-run
      - hm-dry-run
      - test-hm
    desc: Dry activate home-manager config for current user and device
    sources:
      - 'flake.nix'
      - 'flake.lock'
      - '.env'
      - 'flake/*'
      - 'hosts/homes/**/*'
      - 'modules/home/**/*'
      - 'modules/nixos/home/**/*'
      - 'overlays/**/*'
      - 'pkgs/**/*'
      - 'secrets/**/*'
    cmds:
      # Using 'HM_HOST_SLUG=' in '.env' allows for building for specific host on any machine
      - nix run .#home-manager -- switch --dry-run -b backup --show-trace --flake ".#${USER}@${HM_HOST_SLUG:-$(hostname)}"
  
  test:
    aliases: 
      - dry-activate
    desc: Make sure NixOS and/or home-manager will work for current user and device
    cmds:
      - task: test-nixos
      - task: test-home-manager

  ci-home:
    desc: Make sure home-manager will work for generic user and devices
    cmds:
      - nix run .#home-manager -- switch -b backup --flake '.#github-actions@generic'

  home-manager-news:
    aliases: 
      - news
    desc: Show home-manager news
    cmds:
      - nix run .#home-manager -- news --flake ".#${USER}@${HM_HOST_SLUG:-$(hostname)}"

  check:
    desc: Check flake for errors
    cmds:
      - nix flake check -L

  update:
    desc: Bump dependencies
    cmds:
      - nix run .#update-flake-inputs
      - nix run .#commit-selfup
      - nix run .#commit-nvfetcher -L

  help:
    desc: List available tasks
    cmds:
      - task --list-all
