[bauer]
src.github_tag = "matthewbauer/bauer"
fetch.github = "matthewbauer/bauer"

[gauth]
src.github_tag = "pcarrier/gauth"
fetch.github = "pcarrier/gauth"

[gcs]
src.github = "richardwilkes/gcs"
fetch.github = "richardwilkes/gcs"

[mpv-skipsilence]
src.git = "https://github.com/ferreum/mpv-skipsilence"
fetch.github = "ferreum/mpv-skipsilence"