[mpv-skipsilence]
src.git = "https://github.com/ferreum/mpv-skipsilence"
fetch.github = "ferreum/mpv-skipsilence"

[yt-dlp]
src.git = "https://github.com/yt-dlp/yt-dlp"
fetch.github = "yt-dlp/yt-dlp"

[twitchindicator]
src.git = "https://github.com/kuunha/twitchindicator"
fetch.github = "kuunha/twitchindicator"

[chronotube]
# Let's assign versioning manually since it isn't frequently updated
src.manual = "v1.3.0"

#src.github = "necauqua/chronotube"
# From v1.0.0 -> 1.0.0
src.from_pattern = 'v([\d.]+)'
src.to_pattern = '\1'
fetch.url = "https://github.com/necauqua/chronotube/releases/download/v$ver/chronotube-$ver-fx.xpi"

[godot]
 # When updating, change `commitHash` in `./godotjs/default.nix`
src.manual = "4.3-stable"
fetch.github = "godotengine/godot"

[GodotJS]
# See versioning with dependencies: https://github.com/godotjs/GodotJS/wiki/Dependencies
src.github = "godotjs/GodotJS"
fetch.github = "godotjs/GodotJS"

[v8zip]
src.github = "ialex32x/GodotJS-Dependencies"
fetch.url = "https://github.com/ialex32x/GodotJS-Dependencies/releases/download/$ver/$ver.zip"

[undertaker141]
src.github_tag = "AbdelrhmanNile/UnderTaker141"
fetch.url = "https://github.com/AbdelrhmanNile/UnderTaker141/releases/download/latest/UnderTaker141.AppImage"