[mpv-skipsilence]
src.git = "https://github.com/ferreum/mpv-skipsilence"
fetch.github = "ferreum/mpv-skipsilence"

[yt-dlp]
src.git = "https://github.com/yt-dlp/yt-dlp"
fetch.github = "yt-dlp/yt-dlp"

[twitchindicator]
src.git = "https://github.com/kuunha/twitchindicator"
fetch.github = "kuunha/twitchindicator"

[chronotube]
src.manual = "1.3.0"
fetch.url ="https://addons.mozilla.org/firefox/downloads/file/3606813/chronotube-$ver.xpi"