[mpv-skipsilence]
src.git = "https://github.com/ferreum/mpv-skipsilence"
fetch.github = "ferreum/mpv-skipsilence"

[yt-dlp]
src.git = "https://github.com/yt-dlp/yt-dlp"
fetch.github = "yt-dlp/yt-dlp"

[twitchindicator]
src.git = "https://github.com/kuunha/twitchindicator"
fetch.github = "kuunha/twitchindicator"

[chronotube]
# Let's assign versioning manually since it isn't frequently updated
src.manual = "v1.3.0"

#src.github = "necauqua/chronotube"
# From v1.0.0 -> 1.0.0
src.from_pattern = 'v([\d.]+)'
src.to_pattern = '\1'
fetch.url = "https://github.com/necauqua/chronotube/releases/download/v$ver/chronotube-$ver-fx.xpi"