[Hotkey]
EnumerateWithTriggerKeys = "True"
EnumerateForwardKeys = ""
EnumerateBackwardKeys = ""
EnumerateSkipFirst = "False"

["Hotkey/TriggerKeys"]
0 = "Control+space"
1 = "Zenkaku_Hankaku"
2 = "Hangul"

["Hotkey/EnumerateGroupForwardKeys"]
0 = "Super+space"

["Hotkey/EnumerateGroupBackwardKeys"]
0 = "Shift+Super+space"

["Hotkey/ActivateKeys"]
0 = "Hangul_Hanja"

["Hotkey/DeactivateKeys"]
0 = "Hangul_Romaja"

["Hotkey/PrevPage"]
0 = "Up"

["Hotkey/NextPage"]
0 = "Down"

["Hotkey/PrevCandidate"]
0 = "Shift+Tab"

["Hotkey/NextCandidate"]
0 = "Tab"

["Hotkey/TogglePreedit"]
0 = "Control+Alt+P"

[Behavior]
ActiveByDefault = "True"
resetStateWhenFocusIn = "No"
ShareInputState = "All"
PreeditEnabledByDefault = "True"
ShowInputMethodInformation = "True"
showInputMethodInformationWhenFocusIn = "False"
CompactInputMethodInformation = "True"
ShowFirstInputMethodInformation = "True"
DefaultPageSize = "5"
OverrideXkbOption = "False"
CustomXkbOption = ""
EnabledAddons = ""
DisabledAddons = ""
PreloadInputMethod = "True"
AllowInputMethodForPassword = "True"
ShowPreeditForPassword = "True"
AutoSavePeriod = "30"
