{...}: {
  imports = [
    #./adblock
    ./atuin-server
    #./aria
    #./audiobookshelf
    #./backup
    #./blog
    #./calibre-web
    #./drone
    ./fail2ban
    #./flood
    #./forgejo
    #./gitea
    #./grocy
    #./homebox
    #./indexers
    #./jellyfin
    #./komga
    #./lohr
    #./matrix
    #./mealie
    #./miniflux
    #./monitoring
    #./navidrome
    #./nextcloud
    ./nginx
    ./nix-cache
    #./paperless
    #./pdf-edit
    #./podgrab
    #./postgresql
    #./postgresql-backup
    #./pyload
    ./qbittorrent-nox
    #./quassel
    #./rss-bridge
    #./sabnzbd
    #./servarr
    ./ssh-server
    ./tailscale
    #./tandoor-recipes
    #./tlp
    #./transmission
    #./vikunja
    #./wireguard
    #./woodpecker
  ];
}
