# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-skipsilence = {
    pname = "mpv-skipsilence";
    version = "5ae7c3b6f927e728c22fc13007265682d1ecf98c";
    src = fetchFromGitHub {
      owner = "ferreum";
      repo = "mpv-skipsilence";
      rev = "5ae7c3b6f927e728c22fc13007265682d1ecf98c";
      fetchSubmodules = false;
      sha256 = "sha256-fg8vfeb68nr0bTBIvr0FnRnoB48/kV957pn22tWcz1g=";
    };
    date = "2024-05-06";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "0bb39788626002a8a67e925580227952c563c8b9";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "0bb39788626002a8a67e925580227952c563c8b9";
      fetchSubmodules = false;
      sha256 = "sha256-wT3/IAL47w5bQpIo4Gzua2bR7JdM8+EH3Y1mNOPDfxo=";
    };
    date = "2025-02-23";
  };
}
