# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodotJS = {
    pname = "GodotJS";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "godotjs";
      repo = "GodotJS";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-kH6qzix0GMOU++EalTD6BGkuAsQRNYUv2OivnpWBgmw=";
    };
  };
  chronotube = {
    pname = "chronotube";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/necauqua/chronotube/releases/download/v1.3.0/chronotube-1.3.0-fx.xpi";
      sha256 = "sha256-H90V5IZ+ZjLddwiWzMvk5pTY6oL4kCCMZGQXGqRdR/4=";
    };
  };
  fluent-reader = {
    pname = "fluent-reader";
    version = "v1.1.4";
    src = fetchFromGitHub {
      owner = "yang991178";
      repo = "fluent-reader";
      rev = "v1.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-/VBXm6KiwJC/JTKp8m/dkmGmPZ2x2fHYiX9ylw8eDvY=";
    };
  };
  godot = {
    pname = "godot";
    version = "4.3-stable";
    src = fetchFromGitHub {
      owner = "godotengine";
      repo = "godot";
      rev = "4.3-stable";
      fetchSubmodules = false;
      sha256 = "sha256-v2lBD3GEL8CoIwBl3UoLam0dJxkLGX0oneH6DiWkEsM=";
    };
  };
  minecraft-modpack = {
    pname = "minecraft-modpack";
    version = "v2025.07.05-rc2";
    src = fetchurl {
      url = "https://github.com/Joaqim/MinecraftModpack/releases/download/v2025.07.05-rc2/Minecraft-Modpack-v2025.07.05-rc2.mrpack";
      sha256 = "sha256-zaC4TqEODK7aihTuMXzV1MmEQGjTkwxTjA7EV5Dogn8=";
    };
  };
  mpv-skipsilence = {
    pname = "mpv-skipsilence";
    version = "75e1334e513682f0ece6790c614c1fcbd82257cc";
    src = fetchFromGitHub {
      owner = "ferreum";
      repo = "mpv-skipsilence";
      rev = "75e1334e513682f0ece6790c614c1fcbd82257cc";
      fetchSubmodules = false;
      sha256 = "sha256-XmrVZRJAQctIiuznw/fQzs+9+QKOyTnJI2JOEWBWnVA=";
    };
    date = "2025-09-06";
  };
  twitchindicator = {
    pname = "twitchindicator";
    version = "ebf59f896a876c78715eed3755bdcabc0acd42d6";
    src = fetchFromGitHub {
      owner = "kuunha";
      repo = "twitchindicator";
      rev = "ebf59f896a876c78715eed3755bdcabc0acd42d6";
      fetchSubmodules = false;
      sha256 = "sha256-IVnwbWBX4Gi3ZYp1pDaynR2y6XsTGpYKZ9lTTE8Vjas=";
    };
    date = "2025-07-29";
  };
  undertaker141 = {
    pname = "undertaker141";
    version = "v2.10.0";
    src = fetchurl {
      url = "https://github.com/AbdelrhmanNile/UnderTaker141/releases/download/latest/UnderTaker141.AppImage";
      sha256 = "sha256-LBt0or2sH/wyluPbRlhYVP/TqUlJYK34MKfFo8Y8pZU=";
    };
  };
  v8zip = {
    pname = "v8zip";
    version = "v8_12.4.254.21_r13";
    src = fetchurl {
      url = "https://github.com/ialex32x/GodotJS-Dependencies/releases/download/v8_12.4.254.21_r13/v8_12.4.254.21_r13.zip";
      sha256 = "sha256-v+0iW9kveu3tD/QFEX+wKhZ3vbmSTVVCErY1LYfW904=";
    };
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "a183837ec8bb5e28fe6eb3a9d77ea2d0d7a106bd";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "a183837ec8bb5e28fe6eb3a9d77ea2d0d7a106bd";
      fetchSubmodules = false;
      sha256 = "sha256-UGl5peD1WgShYanjpKXs5qlqHncF/gsGFd6EG4mvOhM=";
    };
    date = "2025-09-07";
  };
}
