# Adapted from [1]:
# [1]: https://github.com/kachick/dotfiles/blob/main/.github/workflows/ci-home.yml
# [2]: https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️ # [2]
on: 
  push:
    paths:
      - '.github/workflows/check.yml'
      - '**.nix'
      - 'flake.lock'

jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v11
        with:
          send-statistics: false
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v18
      - name: Inspect flake outputs
        run: |
          echo "Available packages:"
          nix flake show . --json 2>/dev/null | jq '.packages | ."x86_64-linux" | to_entries | map("\(.key) # \(.value.description)")'
          echo "Available overlays:"
          nix flake show . --json 2>/dev/null | jq '.overlays | to_entries | map(.key)'
          echo "Available apps:"
          nix flake show . --json 2>/dev/null | jq '.apps | ."x86_64-linux" | to_entries | map("\(.key)")'
      - run: nix flake check