name: Check Nix Flake
on: 
  push:
    branches: [main]
    paths:
      - '.github/workflows/check.yml'
      - '**.nix'
      - 'flake.lock'
  pull_request:
    paths:
      - '.github/workflows/check.yml'
      - '**.nix'
      - 'flake.lock'
permissions:
  contents: write
  id-token: write
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/flake-checker-action@main