name: Check Nix Flake
name: check
on: push
permissions:
  contents: write
  id-token: write
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/flake-checker-action@main