name: Check Nix Flake
on: 
  push:
    paths:
      - '.github/workflows/check.yml'
      - '**.nix'
      - 'flake.lock'
  pull_request:
    paths:
      - '.github/workflows/check.yml'
      - '**.nix'
      - 'flake.lock'
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Check Nix flake
        run: nix flake check -L