# Taken from [1]:
# [1]: https://github.com/kachick/dotfiles/blob/main/.github/workflows/update-flake-lock-and-ci.ym
name: 🤖🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/update.yml'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:
jobs:
  update:
    if: (github.event_name != 'pull_request') || (!github.event.pull_request.draft)
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@v1.1.9
    with:
      app_id: ${{ vars.APP_ID }}
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      optional-run: |
        nix run .#commit-nvfetcher
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}