name: update
on:
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:
env: 
  LANG: en_US.UTF-8
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PR_CREATE_KEY }}
          fetch-depth: 0
      - name: Cache nvfetcher
        uses: actions/cache@v4
        with:
          path: ~/.local/share/nvfetcher
          key: ${{ runner.os }}-nvfetcher
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.CI_BOT_GH_REPO_TOKEN }}
          # Used only for things like nix-prefetch-*, which do not yet
          # seem to universally support flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name:  Joaqim's GitHub Bot
          git_committer_email: joaqim-ci-bot@joaqim.xyz 
      - run: |
          echo -e '[keys]\ngithub = "${{ secrets.CI_BOT_GH_REPO_TOKEN }}"' > /tmp/github-key.toml
          task update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          branch: bot/update
          delete-branch: true
          title: "Update flake inputs and nvfetcher sources"
          body: |
              - Update flake inputs
              - Update [nvfetcher][1] sources in `./pkgs`
  
              Auto-generated by [create-pull-request][2]

              [1]: https://github.com/berberman/nvfetcher
              [2]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
            dependencies
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
